config/routes.rb
Rails.application.routes.draw do
  root to: 'blogs#index'
  resources :blogs, only: [:index, :new, :create, :show, :edit, :update, :destroy] do
    collection do
      post :confirm
    end
  end
  resources :sessions, only: [:new, :create, :destroy]
  resources :users, only: [:new, :create, :show]
  resources :favorites, only: [:create, :destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/blog.rb
class Blog < ApplicationRecord
  validates :content,presence: true
  validates :title,presence: true
  belongs_to :user
  mount_uploader :image, ImageUploader
end

app/models/user.rb
class User < ApplicationRecord
  has_many :blogs
  validates :name, presence: true, length: {maximum: 30}
  validates :email, presence: true, length: {maximum: 255},
                              format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i }

  before_validation { email.downcase!}
  has_secure_password
  validates :password, length: {minimum: 6 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include SessionsHelper
  before_action :login_required
  private
  def login_required
    redirect_to new_session_path unless current_user
  end
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
  before_action :set_blog, only:[:show,:edit,:update,:destroy ]

  def index
    @blogs = Blog.all
  end

  def new
    @blog = Blog.new
  end

  def show

  end

  def create
    @blog = current_user.blogs.build(blog_params)
    if params[:back]
      render :new
    else
      if @blog.save
        redirect_to blogs_path, notice: "作成しました"
      else
        render :new
      end
    end
  end

  def confirm
    @blog = current_user.blogs.build(blog_params)
    render :new if @blog.invalid?
  end

  def update
    if @blog.update(blog_params)
      redirect_to blogs_path, notice: "編集しました"
    else
      render :edit
    end
  end

  def destroy
    @blog.destroy
    redirect_to blogs_path, notice: "削除しました"
  end

  private

  def set_blog
    @blog = Blog.find(params[:id])
  end

  def blog_params
    params.require(:blog).permit(:title, :content, :user_id, :image, :image_cache)
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  skip_before_action :login_required, only: [:new,:create]
  def new
  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      session[:user_id] = user.id
      redirect_to user_path(user.id)
    else
      flash.now[:danger] = 'ログインに失敗しました'
      render :new
    end
  end

  def destroy
    session.delete(:user_id)
    flash[:notice] = 'ログアウトしました'
    redirect_to new_session_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_action :login_required, only: [:new,:create]
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to user_path(@user.id)
    else
      rnder :new
    end
  end

  def show
    @user = User.find(params[:id])
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :password,
                                  :password_confirmation)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blogs_helper.rb
module BlogsHelper
  def choose_new_or_edit
    if action_name == 'new' || action_name == 'create'
      confirm_blogs_path
    elsif action_name == 'edit'
      blog_path
    end
  end
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  def logged_in?
    current_user.present?
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/blogs/_form.html.erb
<% if @blog.errors.any?%>
  <div id="error_explanation">
    <h2><%=@blog.errors.count %>件のエラーがあります</h2>
    <ul>
    <% @blog.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end%>
<%= form_with(model:@blog, local: true , url:choose_new_or_edit) do |f|%>
  <div class="blog_title">
    <%= f.label :title%>
    <%= f.text_field :title%>
  </div>
  <div class="blog_content">
    <%= f.label :content%>
    <%= f.text_field :content%>
  </div>
  <div class="field">
  <%= f.label :image %>
  <%= f.file_field :image %>
  <%= f.hidden_field :image_cache %>
  </div>
    <%= f.submit "送信"%>
<% end %>

app/views/blogs/confirm.html.erb
<h3>以下の内容で、送信する。</h3>
<%= form_with(model: @blog, local: true) do |form| %>
  <%= form.hidden_field :title %>
  <%= form.hidden_field :content %>
  <p>タイトル:<%= @blog.title %></p>
  <p>本文:<%= @blog.content %></p>
  <%= image_tag(@blog.image.url) if @blog.image && @blog.image.url %>
  <%= form.hidden_field :image_cache %>
  <%= form.submit  "登録する" %>
  <%= form.submit "戻る", name: 'back'%>
<% end %>

app/views/blogs/edit.html.erb
<h1>編集画面</h1>

<%= render 'form'%>

app/views/blogs/index.html.erb
<table>
  <tr>
    <th>タイトル</th>
    <th>内容</th>
    <th>名前</th>
    <th></th>
    <th></th>
  </tr>
  <% @blogs.each do |blog| %>
  <tr>
    <td><%= blog.title %></td>
    <td><%= blog.content %></td>
    <td><%= blog.user.name %></td>
    <td><%= link_to "詳細画面へ", blog_path(blog.id) %></td>
    <td><%= link_to "編集画面へ", edit_blog_path(blog.id), data:{confirm:'本当に編集してよいですか？'}%></td>
    <td><%= link_to "削除する",blog_path(blog.id),method: :delete, data:{confirm:'本当に削除してよいですか？'}%></td>
  </tr>
  <% end %>
</table>
<%= link_to "新規作成画面へ", new_blog_path%>

app/views/blogs/new.html.erb
<h1>新規作成画面</h1>
<%= render 'form'%>

app/views/blogs/show.html.erb
<h1>詳細画面</h1>
<p>名前:<%= @blog.user.name %></p>
<p>タイトル:<%= @blog.title %></p>
<p>内容<%= @blog.content %></p>
<p>
  <strong>Image:</strong>
  <%= image_tag(@blog.image.url) if @blog.image && @blog.image.url %>
</p>
<% unless @blog.user_id == current_user.id %>
  <% if @favorite.present? %>
    <%= link_to 'お気に入り解除する', favorite_path(id: @favorite.id), method: :delete, class: 'btn btn-danger' %>
  <% else %>
    <%= link_to 'お気に入りする', favorites_path(blog_id: @blog.id), method: :post, class: 'btn btn-primary' %>
  <% end %>
<% end %>
<%= link_to 'Edit', edit_blog_path(@blog) %> |
<%= link_to 'Back', blogs_path %>
<%= link_to 'ブログ一覧へ', blogs_path%>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<header>
<h1>Facestyle</h1>
</header>

<html>
  <head>
    <title>Facestyle</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <% flash.each do |key, value| %>
      <%= content_tag(:div, value, class: "#{key}") %>
    <% end %>

    <% if logged_in? %>
      <%= link_to "Profile", user_path(current_user.id) %>
      <%= link_to "ブログ一覧", blogs_path %>
      <%= link_to "Logout", session_path(current_user.id), method: :delete %>
    <% else %>
      <%= link_to "Sign up", new_user_path %>
      <%= link_to "Login", new_session_path %>
    <% end %>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= yield %>
  </body>
  
  <footer class="footer">
  <p>Facestyle</p>
</footer>
</html>

app/views/users/new.html.erb
<h1>Sign up</h1>

<%= form_with(model: @user, local: true) do |f| %>  
  <%= f.label :name %>
  <%= f.text_field :name %>

  <%= f.label :email %>
  <%= f.email_field :email %>

  <%= f.label :password %>
  <%= f.password_field :password %>

  <%= f.label :password_confirmation %>
  <%= f.password_field :password_confirmation %>

  <%= f.submit "Create my account" %>
<% end %>

app/views/users/show.html.erb
<h1><%= @user.name %>のページ</h1>

<p>メールアドレス: <%= @user.email %></p>